volumes:
  local_car_recommendation_postgres_data: {}
  local_car_recommendation_postgres_data_backups: {}

services:
  estimator:
    build:
      context: .
      dockerfile: ./compose/local/estimator/Dockerfile
    image: car_recommendation_model
    container_name: car_recommendation_model
    depends_on:
      - postgres
    volumes:
      - ./app_model:/app
    env_file:
      - ./.envs/.local/.estimator.env
    ports:
      - "8888:8888"
    command: ["/start"]

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: car_recommendation_postgres_local
    container_name: car_recommendation_postgres_local
    volumes:
      - local_car_recommendation_postgres_data:/var/lib/postgresql/data
      - local_car_recommendation_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres.env
    ports:
      - "5432:5432"