volumes:
  production_car_recommendation_postgres_data: {}
  production_car_recommendation_postgres_data_backups: {}

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
    image: car_recommendation_production
    container_name: car_recommendation_production
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.flask.env
      - ./.envs/.production/.postgres.env
    ports:
      - "80:5000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: car_recommendation_production_postgres
    volumes:
      - production_car_recommendation_postgres_data:/var/lib/postgresql/data
      - production_car_recommendation_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres