# Generated by Django 5.0.4 on 2024-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('urlpic', models.URLField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('km', models.CharField(max_length=20)),
                ('gastype', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
